### ISSUE TITLE
Additional fields not showing in the log object

### ISSUE THREAD

**Issue by hanieljazzar** [sainsburys-tech/next-logger#26]
I'm trying to add some fields to the global log, tried in both base and mixin, but the fields only get added locally, but when we deploy to a docker container, they don't show (the default json logs show though). And if I try to make a child, the fields get added under message instead of the higher level log object. Any ideas what can be done to add the fields after deployment to the higher level object?

![image](https://github.com/sainsburys-tech/next-logger/assets/109519090/9aa3c0c2-e773-4fb2-9c0e-4b85830e533c)

**Comment by hanieljazzar** [comment]
false alarm, was a docker file issue, apologies about that

**Comment by davecowart** [comment]
Ended up figuring out my issue. I'm making a standalone build using next.js 14.2 in a multi-stage Dockerfile, so I needed to:
* make sure `next-logger.config.js` was copied to the runtime image, in the same folder as `server.js`
* include `next-logger` and `pino` in `serverComponentsExternalPackages` in next.config.js (even though they're imported in the instrumentation file)
