### ISSUE TITLE
What's about sourcemaps?

### ISSUE THREAD

**Issue by lintellme99** [sainsburys-tech/next-logger#55]
Hi guys, when I see the logs of errors, kinda like `throw new Error(...)`, — I see the minified and uglify code examples, kinda like these:
<img width="1028" alt="Screenshot 2024-08-01 at 20 10 49" src="https://github.com/user-attachments/assets/43a760b0-b261-4948-8f64-865ad15503aa">

I have enabled `sourcemaps` in my `next.config.js`:
```
webpack(config, { dev, isServer }) {
    const newConfig = { ...config }
    
    if (!dev && !isServer) {
      newConfig.devtool = 'source-map'
    }
```

And I see `.map.js` files in my bundle, but I am still struggling with the paths like this:
```
/.next/server/app/page.js:14059:1)
```

Do you know how to fix this and get accurate logs, at least on the server side?

**Comment by atkinchris** [comment]
I suspect this is a Next.js issue itself, rather than `next-logger`.

Do you need to enable this setting: https://nextjs.org/docs/app/api-reference/next-config-js/productionBrowserSourceMaps?

**Comment by lintellme99** [comment]
Oh God, that's really is

Thanks!
Now I don't think that using source maps in production is a good idea, yeah...
It's better to put more logic in the `logs` than to use `trace` on the front end side in production
